sudo: required
language: elixir
elixir: '1.6'
env:
  global:
    - MIX_ENV=test
before_install:
  - docker-compose up -d
before_script:
  - mix format --check-formatted
  - mix credo
script: mix coveralls.travis
services:
  - docker
